services:
  - type: web
    name: cravt-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      # You must add these manually in the dashboard:
      # - DATABASE_URL
      # - FIREBASE_SERVICE_ACCOUNT_JSON
      # - FIREBASE_FRONTEND_CONFIG_JSON
